version: "3.5"
services:
  db:
    image: postgres
    container_name: db-postgress
    platform: linux/x86_64
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
    restart: "always"
    